version: '2'

services:
  enb:
    build: enb_rrh
    networks:
      default:
        ipv4_address: 192.168.12.215
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
  hss:
    build: epc
    command: bash -x -c "/usr/bin/mysqld_safe & sleep 3 && mysql -e \"SET PASSWORD FOR 'root'@'localhost' = PASSWORD('linux');\" && bash -x ./run_hss -i /usr/local/etc/oai/oai_db.sql"
    networks:
      default:
        ipv4_address: 192.168.12.12
    domainname: openair4g.eur
    hostname: hss
  mme:
    build: epc
    command: ./run_mme
    links:
     - hss:hss.openair4g.eur
    networks:
      default:
        ipv4_address: 192.168.12.13
    hostname: mme

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.12.0/24
        gateway: 192.168.12.1

