version: '2'

services:
  enb_limesdr: &ENB_TEMPLATE
    build:
      context: enb_rrh
      args:
        radio: LMSSDR
        target: eNB
    networks:
      default:
        ipv4_address: 192.168.12.215
    privileged: true # enb needs to be able to access USB devices.
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    command: ./lte-softmodem -O /root/enb.band40.tm1.lmssdr.conf --rf-config-file /root/LimeSDR.ini
    volumes:
      - ./enb_rrh/enb.band40.tm1.lmssdr.conf:/root/enb.band40.tm1.lmssdr.conf
      - ./enb_rrh/LimeSDR.ini:/root/LimeSDR.ini
  enb_bladerf:
    <<: *ENB_TEMPLATE
    build:
      context: enb_rrh
      args:
        radio: BLADERF
        target: eNB
  enb_usrp:
    <<: *ENB_TEMPLATE
    build:
      context: enb_rrh
      args:
        radio: USRP
        target: eNB
  ue_limesdr: &UE_TEMPLATE
    build:
      context: enb_rrh
      dockerfile: Dockerfile.xenial
      args:
        radio: LMSSDR
        target: UE
    privileged: true # ue needs to be able to access USB devices.
    devices:
      - "/dev/bus/usb/002/003"
  ue_bladerf:
    <<: *UE_TEMPLATE
    build:
      context: enb_rrh
      dockerfile: Dockerfile.xenial
      args:
        radio: BLADERF
        target: UE
  ue_usrp:
    <<: *UE_TEMPLATE
    build:
      context: enb_rrh
      dockerfile: Dockerfile.xenial
      args:
        radio: USRP
        target: UE
  hss:
    build: epc
    command: bash -x -c "/usr/bin/mysqld_safe & sleep 3 && mysql -e \"SET PASSWORD FOR 'root'@'localhost' = PASSWORD('linux');\" && bash -x ./run_hss -i /usr/local/etc/oai/oai_db.sql"
    networks:
      default:
        ipv4_address: 192.168.12.12
    domainname: openair4g.eur
    hostname: hss
  mme:
    build: epc
    command: ./run_mme
    links:
     - hss:hss.openair4g.eur
    networks:
      default:
        ipv4_address: 192.168.12.11
    hostname: mme
  spgw:
    build: epc
    command: ./run_spgw
    links:
     - hss:hss.openair4g.eur
    privileged: true # spgw needs to be able to modprobe gtp, change iptables, and add network interfaces.
    networks:
      default:
        ipv4_address: 192.168.12.14
      pdn:
        ipv4_address: 172.16.0.2
    hostname: spgw
    volumes:
     - /lib/modules:/lib/modules # so that we can modprobe gtp.
  scanner:
    build: scanner
    privileged: true # scanner needs to be able to access USB devices.
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
  sim_programmer:
    build: sim_programmer
    privileged: true # sim_programmer needs to be able to access USB devices.
    devices:
      - "/dev/bus/usb:/dev/bus/usb"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.12.0/24
        gateway: 192.168.12.1
  pdn:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/16
        gateway: 172.16.0.1
