version: '2'

services:
  enb:
    build: enb_rrh
    networks:
      default:
        ipv4_address: 192.168.12.215
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
  epc:
    build: epc
    networks:
      default:
        ipv4_address: 192.168.12.11

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.12.0/24
        gateway: 192.168.12.1

